apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  labels:
    app: java-app
spec:
  replicas: 2 # هنشغل نسختين من التطبيق عشان لو نسخة وقعت، التانية تفضل شغالة
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        # **مهم جداً:** غير السطر ده لاسم المستخدم بتاعك على Docker Hub
        image: zizoo1566/java-app:build-2
        ports:
        - containerPort: 8090 # البورت اللي التطبيق بيسمع عليه جوه الكونتينر
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
